// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/secrets/v1beta1/resources.proto
// Protobuf Java Version: 4.33.2

package com.google.cloud.secretmanager.v1beta1;

@com.google.protobuf.Generated
public interface SecretPayloadOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.secrets.v1beta1.SecretPayload)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The secret data. Must be no larger than 64KiB.
   * </pre>
   *
   * <code>bytes data = 1;</code>
   *
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
