// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/secretmanager/v1/resources.proto
// Protobuf Java Version: 4.33.2

package com.google.cloud.secretmanager.v1;

@com.google.protobuf.Generated
public interface TopicOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.secretmanager.v1.Topic)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Identifier. The resource name of the Pub/Sub topic that will be published
   * to, in the following format: `projects/&#42;&#47;topics/&#42;`. For publication to
   * succeed, the Secret Manager service agent must have the
   * `pubsub.topic.publish` permission on the topic. The Pub/Sub Publisher role
   * (`roles/pubsub.publisher`) includes this permission.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IDENTIFIER];</code>
   *
   * @return The name.
   */
  java.lang.String getName();
  /**
   *
   *
   * <pre>
   * Identifier. The resource name of the Pub/Sub topic that will be published
   * to, in the following format: `projects/&#42;&#47;topics/&#42;`. For publication to
   * succeed, the Secret Manager service agent must have the
   * `pubsub.topic.publish` permission on the topic. The Pub/Sub Publisher role
   * (`roles/pubsub.publisher`) includes this permission.
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = IDENTIFIER];</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();
}
