// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/cloud/secretmanager/v1beta2/resources.proto
// Protobuf Java Version: 4.33.2

package com.google.cloud.secretmanager.v1beta2;

@com.google.protobuf.Generated
public interface ReplicationOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.secretmanager.v1beta2.Replication)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The [Secret][google.cloud.secretmanager.v1beta2.Secret] will
   * automatically be replicated without any restrictions.
   * </pre>
   *
   * <code>.google.cloud.secretmanager.v1beta2.Replication.Automatic automatic = 1;</code>
   *
   * @return Whether the automatic field is set.
   */
  boolean hasAutomatic();
  /**
   *
   *
   * <pre>
   * The [Secret][google.cloud.secretmanager.v1beta2.Secret] will
   * automatically be replicated without any restrictions.
   * </pre>
   *
   * <code>.google.cloud.secretmanager.v1beta2.Replication.Automatic automatic = 1;</code>
   *
   * @return The automatic.
   */
  com.google.cloud.secretmanager.v1beta2.Replication.Automatic getAutomatic();
  /**
   *
   *
   * <pre>
   * The [Secret][google.cloud.secretmanager.v1beta2.Secret] will
   * automatically be replicated without any restrictions.
   * </pre>
   *
   * <code>.google.cloud.secretmanager.v1beta2.Replication.Automatic automatic = 1;</code>
   */
  com.google.cloud.secretmanager.v1beta2.Replication.AutomaticOrBuilder getAutomaticOrBuilder();

  /**
   *
   *
   * <pre>
   * The [Secret][google.cloud.secretmanager.v1beta2.Secret] will only be
   * replicated into the locations specified.
   * </pre>
   *
   * <code>.google.cloud.secretmanager.v1beta2.Replication.UserManaged user_managed = 2;</code>
   *
   * @return Whether the userManaged field is set.
   */
  boolean hasUserManaged();
  /**
   *
   *
   * <pre>
   * The [Secret][google.cloud.secretmanager.v1beta2.Secret] will only be
   * replicated into the locations specified.
   * </pre>
   *
   * <code>.google.cloud.secretmanager.v1beta2.Replication.UserManaged user_managed = 2;</code>
   *
   * @return The userManaged.
   */
  com.google.cloud.secretmanager.v1beta2.Replication.UserManaged getUserManaged();
  /**
   *
   *
   * <pre>
   * The [Secret][google.cloud.secretmanager.v1beta2.Secret] will only be
   * replicated into the locations specified.
   * </pre>
   *
   * <code>.google.cloud.secretmanager.v1beta2.Replication.UserManaged user_managed = 2;</code>
   */
  com.google.cloud.secretmanager.v1beta2.Replication.UserManagedOrBuilder getUserManagedOrBuilder();

  com.google.cloud.secretmanager.v1beta2.Replication.ReplicationCase getReplicationCase();
}
